# Generated by Django 3.2.4 on 2021-07-02 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210628_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='PostModel',
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'category', 'verbose_name_plural': 'Categories'},
        ),
    ]
